#!/usr/bin/env python3
"""Reporting and logging functions for the text processing tool."""

import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List
from loguru import logger


def generate_summary_report(stats: Dict[str, Any], metadata: Dict[str, Any], output_path: Path) -> None:
    """Generate a summary report of the processing run.

    Args:
        stats: Processing statistics
        metadata: Processing metadata
        output_path: Path to save the summary report
    """
    report = f"""# Processing Summary Report

**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Model**: {metadata.get('model', 'Unknown')}
**Profile**: {metadata.get('profile', 'Default')}

## Statistics

- **Total Files**: {stats.get('total', 0)}
- **Successfully Processed**: {stats.get('processed', 0)}
- **Failed**: {stats.get('failed', 0)}

## Configuration

- **Temperature**: {metadata.get('temperature', 0.0)}
- **Max Tokens**: {metadata.get('max_tokens', 800)}
- **Batch Mode**: {metadata.get('batch_mode', False)}
- **Cache Enabled**: {metadata.get('cache_enabled', False)}

---
*Report generated by TXT Processing Orchestrator*
"""
    output_path.write_text(report)
    logger.info(f"Summary report saved to {output_path}")


def generate_failure_report(errors: List[str], output_path: Path) -> None:
    """Generate a failure report with all errors.

    Args:
        errors: List of error messages
        output_path: Path to save the failure report
    """
    report = f"""# Processing Failures Report

**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Total Failures**: {len(errors)}

## Error Details

"""
    for i, error in enumerate(errors, 1):
        report += f"{i}. {error}\n"

    report += """
---
*Report generated by TXT Processing Orchestrator*
"""
    output_path.write_text(report)
    logger.info(f"Failure report saved to {output_path}")


def create_failure_report(output_dir: Path, txt_file: Path, error_msg: str, file_info: Dict[str, Any]) -> None:
    """Create FAILURE.md file with details about validation failure in output directory.

    Args:
        output_dir: Output directory to save the report
        txt_file: Path to the TXT file that failed
        error_msg: Error message describing the failure
        file_info: File information dictionary (may be empty for read errors)
    """
    failure_content = f"""# Validation Failure Report

**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Failed File**: `{txt_file}`

## Error Details

{error_msg}

## File Information

- File Name: {file_info.get('filename', 'N/A')}
- File Size: {file_info.get('size', 'N/A')} bytes
- Content Length: {file_info.get('content_length', 'N/A')} characters

## Resolution

To fix this issue:
1. Open the file `{txt_file}`
2. Address the validation error: {error_msg}
3. Ensure the TXT file is properly formatted
4. Run the script again

## Validation Requirements

- TXT files must be readable UTF-8 encoded
- TXT must have valid content
- File size must be within processing limits
"""

    failure_file = output_dir / "FAILURE.md"
    failure_file.write_text(failure_content)
    logger.info(f"📝 Failure report created: {failure_file}")


def setup_logging(output_dir: Path) -> None:
    """Set up logging configuration for processing run.
    
    Args:
        output_dir: Directory to save log files
    """
    # Remove default logger
    logger.remove()
    
    # Add console logger with custom format
    logger.add(
        sys.stderr,
        format="<green>{time:HH:mm:ss}</green> | <level>{message}</level>",
        level="INFO"
    )
    
    # Add file logger for this run
    logger.add(
        output_dir / "processing_log.txt",
        format="{time:HH:mm:ss} | {level} | {message}",
        level="INFO"
    )


def generate_summary(output_dir: Path, stats: Dict[str, Any],
                    config: Dict[str, Any], duration: float, total_cost: float = 0.0) -> None:
    """Generate summary report in output directory.
    
    Args:
        output_dir: Directory to save the summary
        stats: Processing statistics
        config: Configuration dictionary
        duration: Processing duration in seconds
        total_cost: Total API cost in USD
    """
    report = f"""# Processing Summary

**Run Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Duration**: {duration:.1f} seconds

## Results
- Files Processed: {stats['processed']}/{stats['total']}
- Successful: {stats['processed']}
- Failed: {stats['failed']}
- Skipped: {stats['skipped']}

## Cost Summary
- **Total Cost**: ${total_cost:.4f} USD
- **Average Cost per File**: ${(total_cost / stats['processed'] if stats['processed'] > 0 else 0):.4f} USD
- **See COST.md for detailed breakdown**

## Configuration
- Model: {config['model']}
- Temperature: {config['temperature']}
- Max Tokens: {config['max_tokens']}
- Fields Removed: {', '.join(config.get('fields_to_remove', []))}
- Batch Mode: {config['batch_mode']}
"""
    
    if config.get('prompt_suffix'):
        report += f"- Prompt Suffix: {config['prompt_suffix']}\n"
    
    if config.get('profile_metadata'):
        metadata = config['profile_metadata']
        report += "\n## Profile\n"
        report += f"- Name: {metadata.get('name', 'Unknown')}\n"
        report += f"- Version: {metadata.get('version', '1.0')}\n"
    
    if stats['errors']:
        report += "\n## Errors\n"
        for error in stats['errors']:
            report += f"- {error}\n"
    
    report += "\n## Statistics\n"
    report += f"- Total API Calls: {stats['processed']}\n"
    if stats['processed'] > 0:
        report += f"- Average Processing Time: {duration/stats['processed']:.1f} seconds per file\n"
    
    summary_file = output_dir / "summary_report.md"
    summary_file.write_text(report)
    logger.info(f"📝 Summary report saved to {summary_file}")